import { Inter } from 'next/font/google'
import { Providers } from './providers';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hotel',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <body>
      <Providers>
        <MainContent>{children}</MainContent>
      </Providers>
    </body>
  </html>
  )
}
